Update
Output at error:
There are 3 duplicate names in the registry. These include: [['ethan', 'Edwards'], ['jordan', 'Olsen'], ['zachary', 'Smith']]
There are 20 students with multiple last names. These include: [['christian', 'Blair-Ramos'], ['aly', 'Cinq-Mars'], ['nathan', 'D Cox'], ['ellie', 'De Groote'], ['brooke', 'Tiffany Demerath'], ['gabe', 'Drake Drake'], ['jorge', 'Hernandez Ramiro'], ['kali', 'Jackson Jackson'], ['joey', 'Johnson-Morgenegg'], ['talmage', 'Michael Kraczek'], ['donna', 'Grace Metcalf'], ['manu', 'Ojeda Servian'], ['matthew', 'Joseph Osborn'], ['aj', 'Jon Peek'], ['audrey', 'Petersen Jones'], ['james', 'Sanford-Luevano'], ['ryan', 'Van Gieson'], ['robert', 'Van Horn'], ['michael', 'Van Shaar'], ['anna', 'Von Niederhausern']]
There are 1033 names in the registry that have been added to the key.
There are 3 participant names (not in the registry) that have been added to the key.
The total size of the key after being initialized is 1510
The number of names resolved in the exact replacement stage is: 2556
The number of remaining names (ambiguous) is: 3036.0
Traceback (most recent call last):

  File "C:\Users\A02234125\Documents\GitHub\EntityResolutionSNA\Main Function.py", line 685, in <module>
    compareKeytoData(keyLocation, dataFileLocation)

  File "C:\Users\A02234125\Documents\GitHub\EntityResolutionSNA\Main Function.py", line 628, in compareKeytoData
    if AmbiguousName[0].isalpha() and AmbiguousName[1].isalpha():

AttributeError: 'float' object has no attribute 'isalpha'